"""init tables

Revision ID: 32639797520a
Revises: 
Create Date: 2026-03-13 18:35:34.081512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32639797520a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_node',
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_gpus', sa.Integer(), nullable=False),
    sa.Column('total_cpu_cores', sa.Integer(), nullable=False),
    sa.Column('total_memory_gb', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name')
    )
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('dl_task',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('template_path', sa.String(length=255), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('current_config_id', sa.BigInteger(), nullable=True),
    sa.Column('basicsr_code_version', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dl_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dl_task_user_id'), ['user_id'], unique=False)

    op.create_table('task_config',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('yaml_path', sa.String(length=255), nullable=False),
    sa.Column('config_json', mysql.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['dl_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version_no', name='uk_task_version')
    )
    with op.batch_alter_table('task_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_config_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_config_user_id'), ['user_id'], unique=False)

    op.create_table('task_run',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('config_id', sa.BigInteger(), nullable=False),
    sa.Column('run_name', sa.String(length=128), nullable=True),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('run_config_path', sa.String(length=255), nullable=False),
    sa.Column('work_dir', sa.String(length=255), nullable=False),
    sa.Column('log_dir', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_dir', sa.String(length=255), nullable=True),
    sa.Column('output_dir', sa.String(length=255), nullable=True),
    sa.Column('tensorboard_dir', sa.String(length=255), nullable=True),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.Column('process_pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('gpu_mode', sa.String(length=32), nullable=False),
    sa.Column('gpu_devices', sa.String(length=128), nullable=True),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['task_config.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['node_id'], ['compute_node.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['dl_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_run_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_run_user_id'), ['user_id'], unique=False)

    op.create_table('gpu_device',
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('gpu_name', sa.String(length=128), nullable=False),
    sa.Column('total_memory_mb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_run_id', sa.BigInteger(), nullable=True),
    sa.Column('last_report_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_run_id'], ['task_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['compute_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'gpu_index', name='uk_node_gpu')
    )
    op.create_table('resource_snapshot',
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('gpu_index', sa.Integer(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('gpu_memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('gpu_temperature', sa.Integer(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['compute_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['task_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_node_time', ['node_id', 'snapshot_time'], unique=False)
        batch_op.create_index('idx_run_time', ['run_id', 'snapshot_time'], unique=False)

    op.create_table('run_artifact',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_artifact_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_artifact_run_id'), ['run_id'], unique=False)

    op.create_table('run_event',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_event_run_id'), ['run_id'], unique=False)

    op.create_table('run_metric',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('step', sa.BigInteger(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metric_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_metric', schema=None) as batch_op:
        batch_op.create_index('idx_run_metric', ['run_id', 'metric_name', 'step'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_metric_run_id'), ['run_id'], unique=False)

    op.create_table('sys_notification',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_run_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_run_id'], ['task_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_notification_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_notification_user_id'))

    op.drop_table('sys_notification')
    with op.batch_alter_table('run_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_metric_run_id'))
        batch_op.drop_index('idx_run_metric')

    op.drop_table('run_metric')
    with op.batch_alter_table('run_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_event_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_event_event_type'))

    op.drop_table('run_event')
    with op.batch_alter_table('run_artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_artifact_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_artifact_artifact_type'))

    op.drop_table('run_artifact')
    with op.batch_alter_table('resource_snapshot', schema=None) as batch_op:
        batch_op.drop_index('idx_run_time')
        batch_op.drop_index('idx_node_time')

    op.drop_table('resource_snapshot')
    op.drop_table('gpu_device')
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_run_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_run_task_id'))

    op.drop_table('task_run')
    with op.batch_alter_table('task_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_config_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_config_task_id'))

    op.drop_table('task_config')
    with op.batch_alter_table('dl_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dl_task_user_id'))

    op.drop_table('dl_task')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index('idx_target')

    op.drop_table('audit_log')
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_user_username'))

    op.drop_table('sys_user')
    op.drop_table('compute_node')
    # ### end Alembic commands ###
