"""init tables

Revision ID: 522737d2c8ca
Revises: b47c732d6f95
Create Date: 2026-03-14 16:40:01.407358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522737d2c8ca'
down_revision = 'b47c732d6f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric_summary_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('best_metric_max_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('best_metric_min_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.drop_column('best_metric_min_json')
        batch_op.drop_column('best_metric_max_json')
        batch_op.drop_column('metric_summary_json')

    # ### end Alembic commands ###
