"""Add training config fields

Revision ID: 9f6e0505dbfb
Revises: 522737d2c8ca
Create Date: 2026-03-14 18:46:18.018592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f6e0505dbfb'
down_revision = '522737d2c8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optim_g_lr', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('optim_d_lr', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ema_decay', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('save_checkpoint_freq', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('print_freq', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_iter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('warmup_iter', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_config', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('warmup_iter')
        batch_op.drop_column('total_iter')
        batch_op.drop_column('print_freq')
        batch_op.drop_column('save_checkpoint_freq')
        batch_op.drop_column('ema_decay')
        batch_op.drop_column('optim_d_lr')
        batch_op.drop_column('optim_g_lr')

    # ### end Alembic commands ###
