"""init tables

Revision ID: b47c732d6f95
Revises: 32639797520a
Create Date: 2026-03-14 13:59:11.199734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47c732d6f95'
down_revision = '32639797520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_from', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parent_run_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'task_run', ['parent_run_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_run_id')
        batch_op.drop_column('resume_from')

    # ### end Alembic commands ###
